version: '3.2'
services:
    database:
        image: sixeyed/atsea-db:mssql
        ports:
            - mode: host
              target: 1433
              published: 1433
        networks:
            - atsea
        deploy:
            endpoint_mode: dnsrr
            placement:
              constraints:
                - 'node.platform.os == windows'

    appserver:
        image: sixeyed/atsea-app:mssql
        ports:
          - mode: ingress
            target: 8080
            published: 8081
        networks:
            - atsea
        deploy:
          endpoint_mode: vip
          placement:
            constraints:
              - 'node.platform.os == linux'

networks:
    atsea:
