version: '3.1'
services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        deploy:
            mode: replicated
            replicas: 1
        ports:
            - 443
            - 80
        networks:
            - gitlab

networks:
    gitlab:
